FinalProject/Controllers/AuthenticationController.cs
using FinalProject.Data;
using FinalProject.Data.Models;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Controllers
{
    public class AuthenticationController : Controller
    {

        public IActionResult Users()
        {
            var allusers = new List<User>()
            { 
                    new User()
                    {
                        Id = 1,
                        Name = "Test1",
                        Email = "Test1",
                        Password = "Test1",                  
                    },

                    new User()
                    {
                        Id = 2,
                        Name = "Test2",
                        Email = "Test2",
                        Password = "Test2",
                    },
                    
                    new User()
                    {
                        Id = 3,
                        Name = "Test3",
                        Email = "Test3",
                        Password = "Test3",
                    }
            };

            return View(allusers);
        }

        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Register()
        {
            return View();
        }
        public IActionResult Remove(int RemoveUser) 
        {
            return View();
        }
    }
}

FinalProject/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

FinalProject/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using FinalProject.Data;
using FinalProject.Data.Models;

namespace FinalProject.Controllers
{
    public class OrdersController : Controller
    {
        public IActionResult Index()
        {
            var allorders = new List<Orden>()
            {
                    new Orden()
                    {
                        Id = 1,
                        ProviderId = 2,
                        UserId = 3,
                        Total = 5000
                    },

                    new Orden()
                    {
                        Id = 2,
                        ProviderId = 3,
                        UserId = 2,
                        Total = 500
                    },

                    new Orden()
                    {
                        Id = 3,           
                        ProviderId = 1,
                        UserId = 1,
                        Total = 2000
                    }
            };
            return View(allorders);
        }
    }
}

FinalProject/Controllers/ProductosController.cs
using Microsoft.AspNetCore.Mvc;
using FinalProject.Data.Models;
using FinalProject.Data;
namespace FinalProject.Controllers
{
    public class ProductosController : Controller
    {
        private readonly AppDbContext _context;

        public ProductosController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {            
            var data = _context.Products.ToList();
            return View();
        }
    }
}

FinalProject/Controllers/ProvidersController.cs
using FinalProject.Data.Models;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Controllers
{
    public class ProvidersController : Controller
    {
        public IActionResult ProvidersView()
        {
            var allproviders = new List<Provider>()
            {
                    new Provider()
                    {
                        Id = 1,
                        Name = "Test1",
                        Contact = "testcontact1",
                        PhoneNumber = "000-000-0000",
                        Email = "Test1@example.com"
                    },

                    new Provider()
                    {
                        Id = 2,
                        Name = "Test2",
                        Contact = "testcontact1",
                        PhoneNumber = "000-000-0000",
                        Email = "Test2@example.com"

                    },

                    new Provider()
                    {
                        Id = 3,
                        Name = "Test3",
                        Contact = "testcontact1",
                        PhoneNumber = "000-000-0000",
                        Email = "Test3@example.com",
                        
                    }
            };

            return View(allproviders);
        }
    }
}

FinalProject/Views/Authentication/Login.cshtml
@{
	ViewData["Title"] = "Log In to your account";
}

<div class="row">
	<div class="col-md-6 offset-md-3">
		<h4>Log in to your account</h4>


		<div class="row">
			<div class="col-md-8 offset-md-2">
				<form asp-controller="Authentication" asp-action="Login">
					<div>
						<label for="emailAddress">Email Address</label>
						<input type="email" class="form-control" id="emailAddress" placeholder="Enter Email"/>
					</div>

					<div>
						<label for="password">Password</label>
						<input type="password" class="form-control" id="password" placeholder="Enter Password" />
					</div>

					<button type="submit" class="btn btn-outline-success mt-2">Login</button>
				</form>
			</div>
		</div>
	</div>
</div>

FinalProject/Views/Authentication/Register.cshtml
@{
	ViewData["Title"] = "Sign Up for a new account";
}

<div class="row">
	<div class="col-md-6 offset-md-3">
		<h4>Register a new account</h4>


		<div class="row">
			<div class="col-md-8 offset-md-2">
				<form asp-controller="Authentication" asp-action="Register">

					<div>
						<label >Full Name</label>
						<input type="text" class="form-control" id="fullName" placeholder="Enter Full Name" />
					</div>

					<div>
						<label>Email Address</label>
						<input type="email" class="form-control" id="emailAddres" placeholder="Enter Email" />
					</div>

					<div>
						<label>Password</label>
						<input type="password" class="form-control" id="password" placeholder="Enter Password" />
					</div>
					<div>
						<label>Confirm Password</label>
						<input type="password" class="form-control" id="confirmPassword" placeholder="Re-Enter Password" />
					</div>
					<button type="submit" class="btn btn-outline-success mt-2">Register</button>
				</form>
			</div>
		</div>
	</div>
</div>

FinalProject/Views/Authentication/Users.cshtml
@model List<User>;

@{
	ViewData["Title"] = "All Users";
}
@foreach (var userdata in Model)
{							
	<div class="container">
		<div class="row row-cols-1 row-cols-md-1 g-4">
			<div class="col">
				<div class="card">
					<div class="card-body">
						<h5 class="card-title">@userdata.Id</h5>
						<p class="card-text">This is an: User</p>
					
						<p class="d-inline-flex gap-1">
							<a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
								Details
							</a>
						</p>
						<div class="collapse" id="collapseExample">
							<div class="card card-body">
								<table class="table table-striped">
									<thead>
										<tr>
											<th>Id</th>
											<th>Name</th>
											<th>Email</th>
										</tr>
									</thead>
									<tbody>
										<tr>										
												<td>@userdata.Id</td>
												<td>@userdata.Name</td>
												<td>@userdata.Email</td>
												<td>
													<a class="btn btn-outline-danger" asp-controller="Authentication" asp-action="Remove" asp-route-RemoveUser="@userdata.Id">Remove</a>
												</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
}

FinalProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Welcome";
}

<div class="text-center">
    <h1 class="display-4">Supply Track</h1>
</div>

FinalProject/Views/Orders/Index.cshtml
@model List<Orden>

@{
	ViewData["Title"] = "All Orders";
}
<div>
	<table class="table">
		<thead>
			<tr>
				<th scope="col">
					Id
				</th>
				<th scope="col">
					Provider Id
				</th>
				<th scope="col">
					User Id
				</th>
				<th scope="col">
					Total
				</th>			
			</tr>
		</thead>

		<tbody>

			@foreach (var order in Model)
			{
				<tr>
					<td>@order.Id</td>
					<td>@order.ProviderId</td>
					<td>@order.UserId</td>
					<td>@order.Total</td>
					<td>
						<a class="btn btn-outline-warning" asp-controller="Productos" asp-action="Edit">Edit</a>
					</td>
					<td>
						<a class="btn btn-outline-secondary" asp-controller="Productos" asp-action="Details">Details</a>
					</td>
					<td>
						<a class="btn btn-outline-danger" asp-controller="Productos" asp-action="Delete">Delete</a>
					</td>
				</tr>
			}			
		</tbody>
	</table>
</div>

FinalProject/Views/Productos/Index.cshtml
@{
	ViewData["Title"] = "Products";
}

<div>
	<table class="table">
		<thead>
			<tr>
				<th scope="col">
					Id
				</th>
				<th scope="col">
					Name
				</th>
				<th scope="col">
					Description
				</th>
				<th scope="col">
					Price
				</th>
				<th scope="col">
					Stock
				</th>
				<th scope="col">
					Category
				</th>
			</tr>
		</thead>

		<tbody>
			<tr>
				<td>1</td>
				<td>Test</td>
				<td>Test</td>
				<td>100</td>
				<td>10</td>
				<td>Test</td>
				<td>
					<a class="btn btn-outline-warning" asp-controller="Productos" asp-action="Edit">Edit</a>
				</td>
				<td>
					<a class="btn btn-outline-secondary" asp-controller="Productos" asp-action="Details">Details</a>
				</td>
				<td>
					<a class="btn btn-outline-danger" asp-controller="Productos" asp-action="Delete">Delete</a>
				</td>							
			</tr>

			<tr>
				<td>1</td>
				<td>Test</td>
				<td>Test</td>
				<td>100</td>
				<td>10</td>
				<td>Test</td>
				<td>
					<a class="btn btn-outline-warning" asp-controller="Productos" asp-action="Edit">Edit</a>
				</td>
				<td>
					<a class="btn btn-outline-secondary" asp-controller="Productos" asp-action="Details">Details</a>
				</td>
				<td>
					<a class="btn btn-outline-danger" asp-controller="Productos" asp-action="Delete">Delete</a>
				</td>
			</tr>
		</tbody>
	</table>
</div>

<div class="container">
	<a class="btn btn-outline-success" asp-controller="Productos" asp-action="Index">Save</a>
</div>

FinalProject/Views/Providers/ProvidersView.cshtml
@model List<Provider>;

@{
	ViewData["Title"] = "All Users";
}
@foreach (var providerdata in Model)
{
	<div class="container">
		<div class="row row-cols-1 row-cols-md-1 g-4">
			<div class="col">
				<div class="card">
					<div class="card-body">
						<h5 class="card-title">@providerdata.Id</h5>
						<p class="card-text">This is a Provider</p>

						<p class="d-inline-flex gap-1">
							<a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
								Details
							</a>
						</p>
						<div class="collapse" id="collapseExample">
							<div class="card card-body">
								<table class="table table-striped">
									<thead>
										<tr>
											<th>Id</th>
											<th>Name</th>
											<th>Contact</th>
											<th>Phone Number</th>
											<th>Email</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td>@providerdata.Id</td>
											<td>@providerdata.Name</td>
											<td>@providerdata.Contact</td>
											<td>@providerdata.PhoneNumber</td>
											<td>@providerdata.Email</td>
											<td>
												<a class="btn btn-outline-danger" asp-controller="Authentication" asp-action="Remove" asp-route-RemoveUser="@providerdata.Id">Remove</a>
											</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
}

FinalProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SupplyTrack</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinalProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SupplyTrack</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Users">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Providers" asp-action="ProvidersView">Providers</a>
                        </li>
                    </ul>
                </div>

                <a class="btn btn-outline-success my-2 my-sm-0 btn-login" asp-controller="Authentication" asp-action="Login">
                    Login
                </a>

                <span style="padding: 5px;"></span>

                <a class="btn btn-outline-success my-2 my-sm-0 btn-login" asp-controller="Authentication" asp-action="Register">
                    Register
                </a>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FinalProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>